version: "3.8"
services:
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80-81:80-81"
      - "443:443"
      - "8901-8999:8901-8999"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy-tier

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Sao_Paulo #optional
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    restart: unless-stopped

networks:
  proxy-tier:
    external: true
