---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Ferramentas:
    - Pi-hole:
        href: http://pi-hole.local/admin
        icon: pi-hole.png
        description: DNS Server and ad-blocker
        widget:
          type: pihole
          url: http://pihole:80
          key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}
        server: my-docker
        container: pihole

    - Nginx-proxy-manager:
        href: http://nginx.local
        icon: nginx-proxy-manager.png
        description: Reverse Proxy
        server: my-docker
        container: nginx-proxy-manager

    - Portainer:
        href: http://portainer.local
        icon: portainer.png
        description: Docker Manager
        server: my-docker
        container: portainer

- Pessoal:
    - Nextcloud:
        href: https://nextcloud.caiol.duckdns.org
        icon: nextcloud.png
        description: Personal Cloud Storage
        siteMonitor: https://nextcloud.caiol.duckdns.org
        widget:
          type: nextcloud
          url: https://nextcloud.caiol.duckdns.org
          username: {{HOMEPAGE_VAR_NEXTCLOUD_USER}}
          password: {{HOMEPAGE_VAR_NEXTCLOUD_PASSWORD}}
        server: my-docker
        container: nextcloud-app

    - Minecraft:
        icon: minecraft.png
        description: Vanilla Minecraft 1.16.1 server
        widget:
          type: minecraft
          url: http://minecraft.local
        server: my-docker
        container: vanilla-minecraft-server

- Midia:
    - Jellyfin:
        href: http://jellyfin.local
        icon: jellyfin.png
        description: Media Server
        siteMonitor: https://jellyfin.europa-server.duckdns.org
        widget:
          type: jellyfin
          url: http://192.168.0.12:8096
          enableBlocks: true
          key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
