version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data

networks:
  default:
    name: proxy-tier
    external: true
