version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 30001:3001

networks:
  default:
    name: proxy-tier
    external: true
